apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 

images:
  - name: /azure-vote-front
    newTag: latest
  - name: /azure-vote-back
    newTag: latest
resources:
  - manifests.yaml